#!/bin/bash
while inotifywait -r -e modify,create,delete,move ./src/ ./shaders/; do
	sleep 0.5
	glslangValidator -V shaders/vertex.vert -o shaders/vertex.spv
	glslangValidator -V shaders/fragment.frag -o shaders/fragment.spv
	cd build; ninja; cd ..
done
